name: On Push non main branches

run-name: '🔫 Pushing changes to ${{ github.ref }} by ${{ github.actor }}'

on:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
