---
name: Source protection

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to run source protection against (e.g., dev, staging, prod)'
        type: string
        required: false
        default: 'dev'
      commitlint-config:
        required: false
        type: string
        description: "The path to the commitlint configuration file (optional)"
        default: '.github/commitlint.config.cjs'
      yamllint-config:
        required: false
        type: string
        description: "The path to the yamllint configuration file (optional)"
        default: '.github/.yamllintrc.yml'

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  validate-commits:
    name: Validate Commits
    runs-on: ubuntu-24.04
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: commitlint
        uses: >-
          wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed
        with:
          configFile: >-
            ${{
              inputs.commitlint-config ||
              '.github/commitlint.config.cjs'
            }}

  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-24.04
    environment:
      name: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: yamllint
        run: |
          CONFIG="${{ inputs.yamllint-config }}"
          # If config is provided and file exists, use it; otherwise, run with default config
          if [ -n "$CONFIG" ] && [ -f "$CONFIG" ]; then
            echo "Using yamllint config file: $CONFIG"
            docker run --rm -v "$(pwd)":/data cytopia/yamllint . -c "$CONFIG"
            if [ $? -eq 0 ]; then
              echo "Lint free! 🎉"
            fi
          else
            echo "No yamllint config provided or file not found, running with default configuration"
            docker run --rm -v "$(pwd)":/data cytopia/yamllint .
            if [ $? -eq 0 ]; then
              echo "Lint free! 🎉"
            fi
          fi
