---
name: Tests

run-name: '🧪 Running tests for ${{ github.ref }}'

on:
  workflow_call:

jobs:
  source-protection:
    name: Source protection
    uses: ./.github/workflows/source-protection.yml
  shellcheck:
    name: ShellCheck
    uses: ./.github/workflows/shellcheck.yml
    with:
      severity: 'error'
      shell-type: 'bash'
